### PR TITLE
errorhandling and small changes

### PR DESCRIPTION
**Pull request by froilainhaeckse**
- [x] leap_web excluded from projectroot
- [x] error-handling
- [x] twitter doc contains info about public twitter account
- [x] production development for readme & secrets
- [x] markdown in README

### CODE REVIEW

**Comment by froilainhaeckse** [comment]
@lilaluca please check and merge if okay!

**Comment by froilainhaeckse** [comment]
by the way, i wasn't able to reproduce varac's problem with setting the tweets to nil when account is private, it gave me also error unauthorized...

**Comment by bl00dymarie** [comment]
Looks great @theaamanda !
Just a thought concerning the description of this error handling: there is no private/public account on Twitter, rather call it "protected tweets", the twitter account itself is visible though. Maybe change to be clearer about the problem? @azul or is it understandable, and it's me mixing it up 
-> "Change your settings "

**Comment by varac** [comment]
@lilaluca "protected tweets" is better i agree

**Review by azul — COMMENTED** [review]
Looks good. You are catching a lot of errors there and turning them into useful messages. :sun_with_face:
:thought_balloon: I have a suggestion for a refactoring and that's all.

**Review by azul — CHANGES_REQUESTED** [review]
hmm... have not figured out the new github review flow... trying again.

**Comment by azul** [comment]
okay... still have not figured out how the new review system works and my suggestion was really minor. So I say after tweaking the error message this is ready to roll :rocket:

**Review by bl00dymarie — CHANGES_REQUESTED** [review]
line 35: = "The account's tweets are protected and cannot be displayed. Please change privacy settings of the corresponding account."

**Pull request merged**
